#!/usr/bin/expect -f

set rpm [lindex $argv 0]
set passphrase [lindex $argv 1]
set email [lindex $argv 2]
set name [lindex $argv 3]

### rpm-sign-expect -- Sign RPMs by sending passphrase and other elements

spawn rpm --define "_gpg_name $name <$email>" --addsign $rpm 
expect -exact "Enter pass phrase: "
send -- "$passphrase\r"
expect eof